### ISSUE TITLE
Question about class DifferentialDriveMixer

### ISSUE THREAD

**Issue by niekun** [wroscoe/donkey#108]
I would like to study the source codes.
I have a question about class DifferentialDriveMixer.
I am confused about below codes
```
l_speed = ((self.left_motor.speed + throttle)/3 - angle/5)
            r_speed = ((self.right_motor.speed + throttle)/3 + angle/5)
```
I want to know why '3' and '5' are used.
What are they stand for? Are they experience values?

**Comment by wroscoe** [comment]
Please use the slack channel for questions. These are values that made the car I was using drive OK.

**Comment by niekun** [comment]
I have no access of the slack channel.
https://donkeycar.slack.com/
Could you add me into slack?
My email address is niekunhit@hotmail.com
