### ISSUE TITLE
Lapack and fortran packages

### ISSUE THREAD

**Issue by tizianofiorenzani** [wroscoe/donkey#109]
I noticed that the installation procedure stops because of **lapack** and **fortran** packages are missing if

```
git clone https://github.com/wroscoe/donkey donkeycar
pip install -e donkeycar
```

You can get them with:

```
sudo apt-get install libblas-dev liblapack-dev
sudo apt-get install gfortran
```

**Comment by wroscoe** [comment]
Thanks. This shouldn't be happening if you're using the disk image on the Pi. Reopen this if you run into it again.
