### ISSUE TITLE
Proposing using RC standard;  Steering on Chan=1 and Throttle on Chan=2

### ISSUE THREAD

**Issue by dlarue** [wroscoe/donkey#149]
There are and will be many RC enthusiasts joinging the DIYRoboCar/Donkey project and it seems appropriate to follow the industry standard since we're using RC vehicles as base platforms.  Following the standard generally reduces support issue.

Changes would have to be made to both the Build document and the Config.py file.

**Comment by wroscoe** [comment]
This is now the default config on master.
