### ISSUE TITLE
Is there any way to view (at least some) code for Raspberry Pi without creating disk image?

### ISSUE THREAD

**Issue by MossMcLaughlin** [wroscoe/donkey#169]
I am doing a similar project and would love to be able to read some of the code for running the Raspberry Pi (particularly how the Pi communicates with the PCA9685 Servo driver). Is there any way for us to read some of the scripts without creating the disk image on our Pi?

**Comment by wroscoe** [comment]
Its all on github... https://github.com/wroscoe/donkey/blob/master/donkeycar/parts/actuators/actuators.py
