### ISSUE TITLE
Create default Pi disk image.

### ISSUE THREAD

**Issue by wroscoe** [wroscoe/donkey#22]
This image would provide the default folder structure, settings and could optionally include keras/tensorflow and opencv.

**Comment by alanwells** [comment]
I captured a clean image during my build (basic setup only, without keras/tensorflow or openCV). I can upload to S3 if it's helpful?

**Comment by wroscoe** [comment]
Thanks @alanwells. Please share a link, I'll try to use it and we can update the image later.

**Comment by alanwells** [comment]
@wroscoe This image was created with the latest donkey code pulled from master around 7AM this morning: https://s3-us-west-1.amazonaws.com/alanwells/donkey/2017-02-11-raspbian-jessie-donkey.iso.zip
