### ISSUE TITLE
manage.py line 17, in <module>     

### ISSUE THREAD

**Issue by ziywang50** [wroscoe/donkey#244]
import donkeycar as dk ModuleNotFoundError: No module named 'donkeycar'
I tried to train my donkey car, but I don't know what is the issue when it displayed this.

**Comment by ziywang50** [comment]
The problem is solved. Ignore this

**Comment by woodrdk** [comment]
I see problem solved may I ask what the fix was as I get this error currently .

**Comment by scitronboy** [comment]
It means you didn't install donkey properly. If you're on windows or mac, make sure your environment is on (anaconda, etc) and if you're on the pi make sure you installed donkey.
