### ISSUE TITLE
我们用自动驾驶local的模式，可是返回的throttle都是0是怎么回事？angle是有数值的。

### ISSUE THREAD

**Issue by RongjieChen** [wroscoe/donkey#253]
我们用自动驾驶local的模式，可是返回的throttle都是0是怎么回事？angle是有数值的。

**Comment by wroscoe** [comment]
I'm sill just learning my greetings in Chinese So I'm not going to be able to help here.

**Comment by wroscoe** [comment]
I don't know Chinese. Sorry.

**Comment by scitronboy** [comment]
Neither do I, I got that Chinese from google translator.

**Comment by dcklee** [comment]
Translating here, he says in autopilot local mode, the throttle settings are always 0. Steering angle however does have values. I believe he is referring to the fact that the car is steering correctly, but the car does not accelerate.

**Comment by mexbo** [comment]
我试过donkeycar的自动驾驶模式，速度完全不好控制，我打算加一个编码器检测速度，形成一个闭环回路，这样小车自动驾驶可能会好一些。这是我做的 deeplearningcar.top

**Comment by dcklee** [comment]
@mexbo If you have the github repository and the hardware speed control sensor details for members to buy it, please share.

**Comment by mexbo** [comment]
我目前速度控制还没有很好解决，小车经常跑出赛道，我打算加上道路检测算法到系统里面。
At present, the speed control has not been well solved. The car often runs out of the track. I plan to add the road detection algorithm to the system.
