### ISSUE TITLE
Refactor imports?

### ISSUE THREAD

**Issue by yconst** [wroscoe/donkey#27]
Donkey is importing all modules in the donkey/ directory, which leads to a lot of unneeded module imports, and breaks in many cases (such as running drive_pi.py, which requires envoy and Keras, even thought they are not used). Can this be architected differently so that only modules needed are imported?

**Comment by wroscoe** [comment]
Yes. I've also had issues with this. There's some balance between having modules accessible after `import donkey as dk`` and not importing modules that won't get used or cause errors on certain platforms. This could be changed in   https://github.com/wroscoe/donkey/blob/master/donkey/__init__.py

**Comment by yconst** [comment]
init checks for os.uname()[1], which gives the node name and can differ from machine to machine. Maybe it's better to check with something like: `os.uname()[4].startsWith("arm")` (per [this SE question](http://raspberrypi.stackexchange.com/questions/5100/detect-that-a-python-program-is-running-on-the-pi))?
