### ISSUE TITLE
Improve small screen UI of vehicle control page

### ISSUE THREAD

**Issue by alanwells** [wroscoe/donkey#55]
Here are some initial thoughts on improvements that I think could be made here:
- Switch to gyroscopic control of vehicle steering and throttle (instead of nipple.js), as this will free up significant screen real estate for other controls. The `DeviceOrientationEvent` API seems to have sufficient cross-platform browser support that it could be used reliably on most iOS and Android phones. More info here: https://developer.mozilla.org/en-US/docs/Web/API/DeviceOrientationEvent
- figure out what the "dead zone" of control should be at the middle of the throttle and steering ranges to make it easy to get to zero throttle/zero steering angle without requiring too precise of a device position. i found I had to figure this out with trial and error on an actual device to get a good feel for it
- optimize the layout for widescreen positioning (more intuitive to hold the phone horizontally when you are using the device position as a steering wheel)
- add an easily accessible start/stop button to the screen to avoid the car running off when you set the phone down :wink:
- Take advantage of the extra on-screen real estate to include controls for:
  - Pilot mode selection
  - Model selection
  - Start/Stop recording toggle

**Comment by wroscoe** [comment]
This sounds so much better. Additional control to add is to start and name new session.

I think I'm getting worse ad driving with the current joystick.
