### ISSUE TITLE
Allow models to be trained off of multiple datasets.

### ISSUE THREAD

**Issue by wroscoe** [wroscoe/donkey#58]
It's currently impossible to train a model on several datasets. You can get around this by creating a dataset out of the sessions you need and training the model on the bigger datasets. Training on datasets too big for memory creates some new problems.
* How can you shuffle the data so that each batch is representative.
* How do you create a generator that loops through the datasets. 

Users should only need to list two datasets in the train.py or explore.py script to use.

**Comment by ShivashishSarvr** [comment]
How did you solved this issue?

**Comment by wroscoe** [comment]
You can use multiple tubs as input by separating the tub names with commas.
